name: Deploy Static Site to Azure Storage

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js (optional if you use a JS build step)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build the static site
        run: |
          npm ci
          npm run build

      - name: Upload to Azure Storage
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az storage blob upload-batch \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
              --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} \
              --destination \$web \
              --source ./dist \
              --overwrite

