on: [push]

name: Run Azure Login With a Service Principal Secret

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to Azure Storage with AAD
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch \
          --destination '$web' \
          --source . \
          --account-name resumesitestorage3072 \
          --auth-mode login
    - name: logout
      run: |
            az logout
      if: always()
